# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Sun Nov  1 12:52:22 2020
# ------------------------------------------------

package:
    name: proj
    version: 7.2.0
source:
    sha256: 2957798e5fe295ff96a2af1889d0428e486363d210889422f76dd744f7885763
    url: http://download.osgeo.org/proj/proj-7.2.0.tar.gz
build:
    number: '0'
    run_exports:
        - proj >=7.2.0,<7.2.1.0a0
    string: h3e70539_0
requirements:
    build:
        - cmake 3.18.3 h39d44d4_0
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.6.20 hecda079_0
        - jpeg 9d h8ffe710_0
        - krb5 1.17.1 hc04afaa_3
        - libcurl 7.71.1 h4b64cdc_8
        - libssh2 1.9.0 hb06d900_5
        - libtiff 4.1.0 h885aae3_6
        - lz4-c 1.9.2 h62dcd97_2
        - openssl 1.1.1h he774522_0
        - sqlite 3.33.0 he774522_1
        - tk 8.6.10 he774522_1
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - xz 5.2.5 h62dcd97_1
        - zlib 1.2.11 h62dcd97_1010
        - zstd 1.4.5 h1f3a1b7_2
    run:
        - libcurl >=7.71.1,<8.0a0
        - libcurl >=7.71.1,<8.0a0
        - libtiff >=4.1.0,<5.0a0
        - libtiff >=4.1.0,<5.0a0
        - sqlite >=3.33.0,<4.0a0
        - sqlite >=3.33.0,<4.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
    run_constrained:
        - proj4 ==999999999999
test:
    commands:
        - if not exist %LIBRARY_LIB%\\proj.lib exit 1
        - echo -105 40 | proj +proj=utm +zone=13 +ellps=WGS84
        - echo -117 30 | cs2cs +proj=latlong +datum=NAD27 +to +proj=latlong +datum=NAD83
        - echo -105 40 | cs2cs +init=epsg:4326 +to +init=epsg:2975
about:
    home: https://proj.org/
    license: MIT
    license_file: COPYING
    summary: Cartographic Projections and Coordinate Transformations Library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - hobu
        - msarahan
        - mwtoews
        - ocefpaf
        - pelson
        - snowman2
        - xylar
